### ISSUE TITLE
The provide core files are NOT working for delay / Serial related functions!!!

### ISSUE THREAD

**Issue by Skammi** [DFRobot/DFRobotDuinoBoard#2]
The provide core files are NOT working for delay / Serial related functions!
Using delay(), delayMicroseconds(), micros() or millis(), with Serial1, that is the Xbee interface, causes hangs in specific instances. One is when waiting for the return response after a control sequence or message is send.

Using these functions at other places doesn't seem to cause issues.

PS, No response from DFrobot after posting the issue in the forum 12 days ago!! @
@lumi3005 @ouki-wang

**Comment by ouki-wang** [comment]
@Skammi 
my ino file
/**************************************/

#include <SPI.h>

void setup()
{
    pinMode(7, OUTPUT);
    digitalWrite(7, HIGH);
    delay(500);
    SPI.begin(); 
    Serial1.begin(115200);
}

void loop() 
{
    digitalWrite(7, LOW);
    SPI.transfer(0x53);
    SPI.transfer(0x00);
    SPI.transfer(0x00);
    SPI.transfer(0x00);
    digitalWrite(7, HIGH);
    delay(1000);   
    Serial1.println(millis());
}


Serial Output:
1500
2500
3500
4500
5500
6500
7500

please show your ino file

**Comment by Skammi** [comment]
Hi Ouki,

Here mine ino file using the esp8266.h library.

#include <esp8266.h>

// TCP_Client_Single.ino

// this example use esp8266 to connect to an Access Point and connect to SINGLE TCP Server which is at the same subnet
// such as the esp8266 is is 192.168.1.3, and the server ip is 192.168.1.1 ,then esp8266 can connect to the server

#include <Arduino.h>
//#include <Utils_lib.h>
#define BEATS 500    // heartBeat interval in milliseconds is 0.5 second
#define HEARTLED 11

#define bluno Serial1
#define console Serial2

#define baudBluno 115200
#define baudConsole 19200

#define ssid		“minenet"		// you need to change it 
#define password	“1A2B3C"

#define serverIP	"10.0.0.162"
#define serverPort	"8888"
Esp8266 wifi;


unsigned long __prevHBT = 0;    // Previous Heart Beat time
unsigned int __deltaT = 1000;   // Time past before we change, default = 1000 1 sec.
bool __light = LOW;

void setup ()
{
  pinMode (HEARTLED, OUTPUT);
  digitalWrite (HEARTLED, LOW);

  delay (2000);        // it will be better to delay 2s to wait esp8266 module OK

  console.begin (baudConsole);
  delay (1000);
  
  console.println ("\n1 After Heartbeat & begin Serial");
  delay (100);
  bluno.begin (115200);
  console.println ("2 After begin Serial1");
  delay (100);

  wifi.begin (&bluno, &console);   //Serial1 is used to communicate with esp8266 module, Serial2 is used to debug
  console.println ("3 After begin wifi");
  delay (100);

 
  if (wifi.connectAP (ssid, password)) {
    wifi.debugPrintln ("connect ap successful !");
  } else {
    wifi.debugPrintln ("connect ap successful !");
    while (true);   // Will hang here forever
  }
  console.println ("4 Before setSingleConnect");

  wifi.setSingleConnect();
  
  console.println ("5 After setSingleConnect");

  if (wifi.connectTCPServer (serverIP, serverPort))
    wifi.debugPrintln ("connect to TCP server successful !");

  String ip_addr;
  ip_addr = wifi.getIP();
  wifi.debugPrintln ("esp8266 ip:" + ip_addr);
}

void loop()
{
 
	int state = wifi.getState();

	switch (state)
	{
	    case WIFI_NEW_MESSAGE: 
       		 wifi.debugPrintln ("new message!");
     		 wifi.debugPrintln (wifi.getMessage ());   // Print the message on the console
	     	 wifi.sendMessage (wifi.getMessage ());		// send the message to TCP server what it has received
	     	 wifi.setState (WIFI_IDLE);
	      break;
	    case WIFI_CLOSED :							//reconnet to the TCP server 
	      wifi.debugPrintln ("server is closed! and trying to reconnect it!");
	      if (wifi.connectTCPServer (serverIP, serverPort)) {
	      	wifi.debugPrintln ("reconnect OK!");
	      	wifi.setState (WIFI_IDLE);
	      }
	      else {
	      	wifi.debugPrintln("reconnect fail");
	      	wifi.setState(WIFI_CLOSED);
	      }
	      break;
	    case WIFI_IDLE :							
	    	int sta = wifi.checkMessage(); 
	    	wifi.setState(sta);
	    	break;
	}
 
  unsigned long currentT = millis();      // Take time time sample
  if ( currentT - __prevHBT >= __deltaT)    // Delta time passed?
  {
    __prevHBT = currentT;         // Reset previous measure
    __light = (__light) ? LOW : HIGH;   // toggle light
    digitalWrite (HEARTLED, __light);    // and display
  }

  delay (100);
}





The Serial 2 output.

1 After Heartbeat & begin Serial
2 After begin Serial1
3 After begin wifi

The code seems to hang in "wifi.connectAP (ssid, password)" of the DFrobot ESP8266 library.

By the way the same code works fine on an UNO with the I/O expansion shield.

So I did some further analysis.

In the library a mix is used of millis() and delay() to get time delay's
In "wifi.connectAP (ssid, password)” millis() is used. However in the checkMode() routine which is called by wifi.connectAP delay(200) is used!
When I remove the delay(200) the routine works fine. By the way you can remove the delay because there is a millis() with a time out in readData.

char Esp8266::checkMode() {
	clearBuf();
	write("AT+CWMODE?");
	//delay(200);
	String str = readData();

	if (str.indexOf('1') > 0 )  
		return '1';
	else if (str.indexOf('2') > 0)
		return '2';
	else if (str.indexOf('3') > 0)
		return '3';
	else 
		return '0';
}


But the example will hang in another place in the DFrobot ESP8266 library where delay is used.

Output:
1 After Heartbeat & begin Serial
2 After begin Serial1
3 After begin wifi
connect ap successful !
4 Before setSingleConnect

In setSingleConnect setMux is called which uses a delay (100) again.

Best regards,
Jacob
'
_______________________________
Jacob Kamminga

jacob.kamminga@mac.com

Perfection is achieved,
not when there is nothing more to add,
but when there is nothing left to take away.

Antoine de Saint-Exupéry

**Comment by WeMakeIt1995** [comment]
@Skammi 
Hi, try to modify HardSerial.h in your M0 SDK floder, change SERIAL_BUFFER_SIZE to 128 at line 43.

**Comment by Skammi** [comment]
Hi.

Thank you, that did the trick it seems to work ok now.

Cheers,
Jacob

Perfection is achieved,
not when there is nothing more to add,
but when there is nothing left to take away.

Antoine de Saint-Exupéry

**Comment by Skammi** [comment]
Closing the issues, as after the update of SERIAL_BUFFER_SIZE to 128, all works fine
